[package]
name = "ws"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
axum = { workspace = true, features = ["ws"] }
serde.workspace = true
tokio.workspace = true
uuid.workspace = true

shared = { path = "../shared" }
thiserror.workspace = true
